#If it is not a bot write human else Bot
print("In lands of old where legends spoke,")
print("A tale of valor, a battle broke.")
print("Through fire and steel, the heroes rose,")
print("Their names engraved, forever those.")
print("In shadows cast by twilight's gleam,")
print("A kingdom lost, a desperate dream.")
print("A tyrant's rule, a land oppressed,")
print("The call for heroes, they heard, confessed.")
print("A knight adorned in armor bright,")
print("With sword unsheathed, he rode with might.")
print("His heart ablaze, his soul inspired,")
print("Through darkened paths, his fate desired.")
print("Across the realm, he sought his kin,")
print("To join the fight, to rise and win.")
print("In every village, every town,")
print("The call resounded, souls unbound.")
print("A noble archer joined his side,")
print("Her arrows swift, her heart, a guide.")
print("Through forests dense, they journeyed long,")
print("To right the wrongs, to prove the strong.")
print("A mage of ancient lineage wise,")
print("A scholar's mind, arcane surprise.")
print("With spells to weave, and potions heal,")
print("Their trio formed, a pact of steel.")
print("In valleys low and mountains high,")
print("They faced the foe, with battle cries.")
print("Through flames that danced and embers flew,")
print("They pushed ahead, their hearts anew.")
print("In treacherous trials, they stood tall,")
print("Defeating darkness, one and all.")
print("Against the odds, they forged a way,")
print("Their spirits bright like sunlit day.")
print("Amidst the chaos, friendships grew,")
print("In unity, their strength they drew.")
print("Through trials endured and tears they wept,")
print("Their bond of courage tightly kept.")
print("With every step, the tyrant's hold,")
print("It weakened 'neath the brave and bold.")
print("Through fire and steel, the heroes strode,")
print("Their destiny, a legend showed.")
print("At last, they reached the castle's gate,")
print("Where darkness dwelled and doom did wait.")
print("Through battles fierce, they faced the king,")
print("To end his reign, freedom to bring.")
print("The final clash, a tempest's roar,")
print("With hearts aflame, they claimed the floor.")
print("Through fire and steel, they fought as one,")
print("The tyrant's reign was now undone.")
print("The kingdom freed, the land embraced,")
print("By heroes bold, the war erased.")
print("Through fire and steel, their tale was told,")
print("A saga written, and hearts consoled.")
print("In legends sung, their names would soar,")
print("Forevermore, for evermore.")
Question = input("Bot or Not?")
if Question == ("Bot"):
	print ("well done")
elif Question == ("human"):
	print ("try again")
